// Prize2Pride Host Couples Configuration
// 64 Stunning Hyper-Realistic Host Couples for Live Show Lessons

export interface HostCouple {
  id: string;
  name: string;
  maleName: string;
  femaleName: string;
  category: 'ethnic' | 'lesson' | 'level' | 'tunisian';
  theme: string;
  description: string;
  imagePath: string;
  specialty?: string;
  level?: string;
}

// Ethnic Diversity Couples
export const ethnicCouples: HostCouple[] = [
  {
    id: 'couple-01-european',
    name: 'European Hosts',
    maleName: 'Alexander',
    femaleName: 'Isabella',
    category: 'ethnic',
    theme: 'European Elegance',
    description: 'Sophisticated European couple in designer evening wear',
    imagePath: '/avatars/pairs/couple-01-european.png',
  },
  {
    id: 'couple-02-asian',
    name: 'Asian Hosts',
    maleName: 'Kenji',
    femaleName: 'Yuki',
    category: 'ethnic',
    theme: 'East Asian Style',
    description: 'Elegant East Asian couple in modern formal attire',
    imagePath: '/avatars/pairs/couple-02-asian.png',
  },
  {
    id: 'couple-03-african',
    name: 'African Hosts',
    maleName: 'Kwame',
    femaleName: 'Amara',
    category: 'ethnic',
    theme: 'African Royalty',
    description: 'Stunning African couple in luxurious formal wear',
    imagePath: '/avatars/pairs/couple-03-african.png',
  },
  {
    id: 'couple-04-latino',
    name: 'Latino Hosts',
    maleName: 'Diego',
    femaleName: 'Sofia',
    category: 'ethnic',
    theme: 'Latin Passion',
    description: 'Vibrant Latino couple in glamorous attire',
    imagePath: '/avatars/pairs/couple-04-latino.png',
  },
  {
    id: 'couple-05-middleeastern',
    name: 'Middle Eastern Hosts',
    maleName: 'Omar',
    femaleName: 'Layla',
    category: 'ethnic',
    theme: 'Arabian Nights',
    description: 'Elegant Middle Eastern couple in sophisticated style',
    imagePath: '/avatars/pairs/couple-05-middleeastern.png',
  },
];

// Casino Show Style Couples
export const showCouples: HostCouple[] = [
  {
    id: 'couple-11-show-european',
    name: 'European Show Hosts',
    maleName: 'Sebastian',
    femaleName: 'Victoria',
    category: 'ethnic',
    theme: 'Las Vegas Glamour',
    description: 'European couple in casino-show studio with gold & diamond branding',
    imagePath: '/avatars/pairs/couple-11-show-european.png',
  },
  {
    id: 'couple-12-show-asian',
    name: 'Asian Show Hosts',
    maleName: 'Hiroshi',
    femaleName: 'Sakura',
    category: 'ethnic',
    theme: 'Tokyo Nights',
    description: 'Asian couple in spectacular show studio setting',
    imagePath: '/avatars/pairs/couple-12-show-asian.png',
  },
  {
    id: 'couple-13-show-african',
    name: 'African Show Hosts',
    maleName: 'Kofi',
    femaleName: 'Zara',
    category: 'ethnic',
    theme: 'African Glamour',
    description: 'African couple in dazzling casino-show environment',
    imagePath: '/avatars/pairs/couple-13-show-african.png',
  },
  {
    id: 'couple-14-show-latino',
    name: 'Latino Show Hosts',
    maleName: 'Mateo',
    femaleName: 'Valentina',
    category: 'ethnic',
    theme: 'Latin Fire',
    description: 'Latino couple in vibrant show studio',
    imagePath: '/avatars/pairs/couple-14-show-latino.png',
  },
  {
    id: 'couple-15-show-middleeast',
    name: 'Middle Eastern Show Hosts',
    maleName: 'Khalid',
    femaleName: 'Nadia',
    category: 'ethnic',
    theme: 'Desert Royalty',
    description: 'Middle Eastern couple in luxurious show setting',
    imagePath: '/avatars/pairs/couple-15-show-middleeast.png',
  },
];

// Lesson-Themed Couples
export const lessonCouples: HostCouple[] = [
  {
    id: 'lesson-grammar-hosts',
    name: 'Grammar Masters',
    maleName: 'Professor William',
    femaleName: 'Dr. Elizabeth',
    category: 'lesson',
    theme: 'Grammar Studio',
    description: 'Teaching grammar at interactive whiteboard',
    imagePath: '/avatars/pairs/lesson-grammar-hosts.png',
    specialty: 'Grammar & Sentence Structure',
  },
  {
    id: 'lesson-conversation-hosts',
    name: 'Conversation Coaches',
    maleName: 'Coach Michael',
    femaleName: 'Coach Sarah',
    category: 'lesson',
    theme: 'Talk Show',
    description: 'Demonstrating natural conversation on luxury couch',
    imagePath: '/avatars/pairs/lesson-conversation-hosts.png',
    specialty: 'Speaking & Dialogue',
  },
  {
    id: 'lesson-vocabulary-hosts',
    name: 'Vocabulary Champions',
    maleName: 'Host David',
    femaleName: 'Host Emma',
    category: 'lesson',
    theme: 'Word Game Show',
    description: 'Game show style vocabulary teaching',
    imagePath: '/avatars/pairs/lesson-vocabulary-hosts.png',
    specialty: 'Vocabulary Building',
  },
  {
    id: 'lesson-pronunciation-hosts',
    name: 'Pronunciation Experts',
    maleName: 'Voice Coach James',
    femaleName: 'Voice Coach Olivia',
    category: 'lesson',
    theme: 'Sound Studio',
    description: 'Teaching pronunciation with golden microphones',
    imagePath: '/avatars/pairs/lesson-pronunciation-hosts.png',
    specialty: 'Pronunciation & Accent',
  },
  {
    id: 'lesson-business-hosts',
    name: 'Business English Pros',
    maleName: 'Executive Robert',
    femaleName: 'Executive Catherine',
    category: 'lesson',
    theme: 'Boardroom',
    description: 'Professional business English in executive setting',
    imagePath: '/avatars/pairs/lesson-business-hosts.png',
    specialty: 'Business Communication',
  },
  {
    id: 'lesson-travel-hosts',
    name: 'Travel Guides',
    maleName: 'Guide Thomas',
    femaleName: 'Guide Maria',
    category: 'lesson',
    theme: 'World Explorer',
    description: 'Travel English with world map backdrop',
    imagePath: '/avatars/pairs/lesson-travel-hosts.png',
    specialty: 'Travel & Tourism English',
  },
  {
    id: 'lesson-culture-hosts',
    name: 'Culture Ambassadors',
    maleName: 'Ambassador John',
    femaleName: 'Ambassador Grace',
    category: 'lesson',
    theme: 'Hollywood Premiere',
    description: 'American culture with Hollywood glamour',
    imagePath: '/avatars/pairs/lesson-culture-hosts.png',
    specialty: 'American Culture & Customs',
  },
  {
    id: 'lesson-idioms-hosts',
    name: 'Idiom Specialists',
    maleName: 'Host Ryan',
    femaleName: 'Host Jessica',
    category: 'lesson',
    theme: 'Expression Studio',
    description: 'Teaching idioms with speech bubble props',
    imagePath: '/avatars/pairs/lesson-idioms-hosts.png',
    specialty: 'Idioms & Expressions',
  },
  {
    id: 'lesson-daily-hosts',
    name: 'Daily Life Coaches',
    maleName: 'Coach Daniel',
    femaleName: 'Coach Emily',
    category: 'lesson',
    theme: 'Living Room',
    description: 'Everyday conversation in cozy setting',
    imagePath: '/avatars/pairs/lesson-daily-hosts.png',
    specialty: 'Daily Conversation',
  },
  {
    id: 'lesson-academic-hosts',
    name: 'Academic Mentors',
    maleName: 'Dr. Benjamin',
    femaleName: 'Dr. Charlotte',
    category: 'lesson',
    theme: 'Library',
    description: 'Academic English in elegant library',
    imagePath: '/avatars/pairs/lesson-academic-hosts.png',
    specialty: 'Academic Writing & Research',
  },
];

// Level-Based Couples (A1-C2)
export const levelCouples: HostCouple[] = [
  {
    id: 'level-A1-beginner-hosts',
    name: 'A1 Beginner Guides',
    maleName: 'Friendly Alex',
    femaleName: 'Friendly Amy',
    category: 'level',
    theme: 'Rainbow Welcome',
    description: 'Welcoming hosts for absolute beginners',
    imagePath: '/avatars/pairs/level-A1-beginner-hosts.png',
    level: 'A1',
  },
  {
    id: 'level-A2-elementary-hosts',
    name: 'A2 Elementary Hosts',
    maleName: 'Guide Chris',
    femaleName: 'Guide Claire',
    category: 'level',
    theme: 'Building Blocks',
    description: 'Encouraging hosts for elementary learners',
    imagePath: '/avatars/pairs/level-A2-elementary-hosts.png',
    level: 'A2',
  },
  {
    id: 'level-B1-intermediate-hosts',
    name: 'B1 Intermediate Hosts',
    maleName: 'Mentor Mark',
    femaleName: 'Mentor Michelle',
    category: 'level',
    theme: 'Progress Path',
    description: 'Confident hosts for intermediate level',
    imagePath: '/avatars/pairs/level-B1-intermediate-hosts.png',
    level: 'B1',
  },
  {
    id: 'level-B2-upper-hosts',
    name: 'B2 Upper Intermediate Hosts',
    maleName: 'Expert Eric',
    femaleName: 'Expert Elena',
    category: 'level',
    theme: 'Debate Stage',
    description: 'Professional hosts for upper intermediate',
    imagePath: '/avatars/pairs/level-B2-upper-hosts.png',
    level: 'B2',
  },
  {
    id: 'level-C1-advanced-hosts',
    name: 'C1 Advanced Hosts',
    maleName: 'Master Marcus',
    femaleName: 'Master Marina',
    category: 'level',
    theme: 'Executive Suite',
    description: 'Elite hosts for advanced learners',
    imagePath: '/avatars/pairs/level-C1-advanced-hosts.png',
    level: 'C1',
  },
  {
    id: 'level-C2-mastery-hosts',
    name: 'C2 Mastery Champions',
    maleName: 'Champion Charles',
    femaleName: 'Champion Christina',
    category: 'level',
    theme: 'Royal Gala',
    description: 'Crown hosts for mastery level',
    imagePath: '/avatars/pairs/level-C2-mastery-hosts.png',
    level: 'C2',
  },
];

// Tunisian Traditional Couples (20 couples)
export const tunisianCouples: HostCouple[] = [
  {
    id: 'tunisian-couple-01',
    name: 'Tunisian Hosts 1',
    maleName: 'Youssef',
    femaleName: 'Amira',
    category: 'tunisian',
    theme: 'White Jebba & Royal Blue Kaftan',
    description: 'Traditional Tunisian elegance with gold embroidery',
    imagePath: '/avatars/pairs/tunisian-couple-01.png',
  },
  {
    id: 'tunisian-couple-02',
    name: 'Tunisian Hosts 2',
    maleName: 'Ahmed',
    femaleName: 'Fatma',
    category: 'tunisian',
    theme: 'Farmla Vest & Sefsari Gown',
    description: 'Traditional Farmla with Chechia hat and cream Sefsari',
    imagePath: '/avatars/pairs/tunisian-couple-02.png',
  },
  {
    id: 'tunisian-couple-03',
    name: 'Tunisian Hosts 3',
    maleName: 'Mohamed',
    femaleName: 'Salma',
    category: 'tunisian',
    theme: 'Burgundy Wedding Style',
    description: 'Red and gold ceremonial dress with headpiece',
    imagePath: '/avatars/pairs/tunisian-couple-03.png',
  },
  {
    id: 'tunisian-couple-04',
    name: 'Tunisian Hosts 4',
    maleName: 'Karim',
    femaleName: 'Yasmine',
    category: 'tunisian',
    theme: 'Navy Modern & Emerald Kaftan',
    description: 'Modern Tunisian designer with Jasmine patterns',
    imagePath: '/avatars/pairs/tunisian-couple-04.png',
  },
  {
    id: 'tunisian-couple-05',
    name: 'Tunisian Hosts 5',
    maleName: 'Sami',
    femaleName: 'Nour',
    category: 'tunisian',
    theme: 'White Jebba & Purple Ceremonial',
    description: 'Sfax-style embroidery with Fibula brooches',
    imagePath: '/avatars/pairs/tunisian-couple-05.png',
  },
  {
    id: 'tunisian-couple-06',
    name: 'Tunisian Hosts 6',
    maleName: 'Amine',
    femaleName: 'Ines',
    category: 'tunisian',
    theme: 'Black Jebba & Turquoise Keswa',
    description: 'Gold geometric embroidery with Meskia jewelry',
    imagePath: '/avatars/pairs/tunisian-couple-06.png',
  },
  {
    id: 'tunisian-couple-07',
    name: 'Tunisian Hosts 7',
    maleName: 'Hamza',
    femaleName: 'Mariem',
    category: 'tunisian',
    theme: 'Barnous Cape & Pink Bridal',
    description: 'Traditional Barnous with Rihana headpiece',
    imagePath: '/avatars/pairs/tunisian-couple-07.png',
  },
  {
    id: 'tunisian-couple-08',
    name: 'Tunisian Hosts 8',
    maleName: 'Fares',
    femaleName: 'Rania',
    category: 'tunisian',
    theme: 'Charcoal Modern & Orange Fouta',
    description: 'Modern Tunisian with Fouta-inspired design',
    imagePath: '/avatars/pairs/tunisian-couple-08.png',
  },
  {
    id: 'tunisian-couple-09',
    name: 'Tunisian Hosts 9',
    maleName: 'Bilel',
    femaleName: 'Sarra',
    category: 'tunisian',
    theme: 'Ivory Sfax & Teal Kaftan',
    description: 'Kairouan-style with Jasmine motifs and Khamsa jewelry',
    imagePath: '/avatars/pairs/tunisian-couple-09.png',
  },
  {
    id: 'tunisian-couple-10',
    name: 'Tunisian Hosts 10',
    maleName: 'Wassim',
    femaleName: 'Leila',
    category: 'tunisian',
    theme: 'Navy Farmla & Coral Ceremonial',
    description: 'Traditional Farmla vest with pearl accessories',
    imagePath: '/avatars/pairs/tunisian-couple-10.png',
  },
  {
    id: 'tunisian-couple-11',
    name: 'Tunisian Hosts 11',
    maleName: 'Rami',
    femaleName: 'Donia',
    category: 'tunisian',
    theme: 'Sage Green & Lavender',
    description: 'Elegant sage Jebba with lavender Kaftan',
    imagePath: '/avatars/pairs/tunisian-couple-11.png',
  },
  {
    id: 'tunisian-couple-12',
    name: 'Tunisian Hosts 12',
    maleName: 'Anis',
    femaleName: 'Hiba',
    category: 'tunisian',
    theme: 'Beige Kairouan & Gold/White Bridal',
    description: 'Royal wedding style with elaborate headpiece',
    imagePath: '/avatars/pairs/tunisian-couple-12.png',
  },
  {
    id: 'tunisian-couple-13',
    name: 'Tunisian Hosts 13',
    maleName: 'Nizar',
    femaleName: 'Asma',
    category: 'tunisian',
    theme: 'Black Embroidered & Rose Gold',
    description: 'Modern elegance with crystal embellishments',
    imagePath: '/avatars/pairs/tunisian-couple-13.png',
  },
  {
    id: 'tunisian-couple-14',
    name: 'Tunisian Hosts 14',
    maleName: 'Tarek',
    femaleName: 'Manel',
    category: 'tunisian',
    theme: 'Maroon Jebba & Sapphire Blue',
    description: 'Gold geometric patterns with Khomsa pendant',
    imagePath: '/avatars/pairs/tunisian-couple-14.png',
  },
  {
    id: 'tunisian-couple-15',
    name: 'Tunisian Hosts 15',
    maleName: 'Mehdi',
    femaleName: 'Rim',
    category: 'tunisian',
    theme: 'Cream Farmla & Forest Green',
    description: 'Burgundy embroidery with Jasmine patterns',
    imagePath: '/avatars/pairs/tunisian-couple-15.png',
  },
  {
    id: 'tunisian-couple-16',
    name: 'Tunisian Hosts 16',
    maleName: 'Zied',
    femaleName: 'Olfa',
    category: 'tunisian',
    theme: 'Royal Blue & Champagne Gold',
    description: 'Silver thread with crystal beading and Rihana headpiece',
    imagePath: '/avatars/pairs/tunisian-couple-16.png',
  },
  {
    id: 'tunisian-couple-17',
    name: 'Tunisian Hosts 17',
    maleName: 'Seif',
    femaleName: 'Cyrine',
    category: 'tunisian',
    theme: 'White Wedding & Red/Gold Bridal',
    description: 'Traditional Tunisian wedding style with crown',
    imagePath: '/avatars/pairs/tunisian-couple-17.png',
  },
  {
    id: 'tunisian-couple-18',
    name: 'Tunisian Hosts 18',
    maleName: 'Oussama',
    femaleName: 'Emna',
    category: 'tunisian',
    theme: 'Navy Blazer & Peach Evening',
    description: 'Modern Tunisian designer with diamond earrings',
    imagePath: '/avatars/pairs/tunisian-couple-18.png',
  },
  {
    id: 'tunisian-couple-19',
    name: 'Tunisian Hosts 19',
    maleName: 'Skander',
    femaleName: 'Wiem',
    category: 'tunisian',
    theme: 'Olive Green & Violet Kaftan',
    description: 'Silver Jasmine embroidery with Kholkhal jewelry',
    imagePath: '/avatars/pairs/tunisian-couple-19.png',
  },
  {
    id: 'tunisian-couple-20',
    name: 'Tunisian Hosts 20',
    maleName: 'Aymen',
    femaleName: 'Nesrine',
    category: 'tunisian',
    theme: 'Black/Gold Ceremonial & Royal Wedding',
    description: 'Grand finale with Chechia hat and diamond tiara',
    imagePath: '/avatars/pairs/tunisian-couple-20.png',
  },
];

// All couples combined
export const allHostCouples: HostCouple[] = [
  ...ethnicCouples,
  ...showCouples,
  ...lessonCouples,
  ...levelCouples,
  ...tunisianCouples,
];

// Helper function to get couples by category
export function getCouplesByCategory(category: HostCouple['category']): HostCouple[] {
  return allHostCouples.filter(couple => couple.category === category);
}

// Helper function to get couple by level
export function getCoupleByLevel(level: string): HostCouple | undefined {
  return levelCouples.find(couple => couple.level === level);
}

// Helper function to get random couple
export function getRandomCouple(): HostCouple {
  return allHostCouples[Math.floor(Math.random() * allHostCouples.length)];
}

// Helper function to get couple for lesson type
export function getCoupleForLessonType(lessonType: string): HostCouple | undefined {
  const typeMap: Record<string, string> = {
    'grammar': 'lesson-grammar-hosts',
    'conversation': 'lesson-conversation-hosts',
    'vocabulary': 'lesson-vocabulary-hosts',
    'pronunciation': 'lesson-pronunciation-hosts',
    'business': 'lesson-business-hosts',
    'travel': 'lesson-travel-hosts',
    'culture': 'lesson-culture-hosts',
    'idioms': 'lesson-idioms-hosts',
    'daily': 'lesson-daily-hosts',
    'academic': 'lesson-academic-hosts',
  };
  
  const coupleId = typeMap[lessonType.toLowerCase()];
  return lessonCouples.find(couple => couple.id === coupleId);
}
